Prevent /tmp from filling up.
osuosl-cookbooks/nodejs-webapp pull request #7
Opened 2016-09-26 17:20 UTC by LyonesGamer

For some reason, every time chef runs the `npm -g install npm` bash block in this cookbook, a folder containing the unpacked tarball of the newest npm version is left in /tmp. Npm *should* be cleaning this folder up to prevent high disk usage, but for some reason it doesn't when run from chef. This is a temporary fix to prevent Chef from filling up the /tmp folder by deleting these folders manually.

2016-09-26 20:53 UTC, ramereth commented on providers/default.rb
> +    command "find . -depth -iname 'npm-*' -type d -exec rm -r \"{}\" \\;"
I don't feel good about this. Can you set it directly to ``find /tmp ...``. I know that cwd is set to it, but it'll make me feel better if the command actually does what you're wanting.

2016-09-26 20:53 UTC, ramereth requested changes
Tests?

2016-09-28 16:44 UTC, LyonesGamer commented on providers/default.rb
> +    command "find . -depth -iname 'npm-*' -type d -exec rm -r \"{}\" \\;"
Fixed that and added tests.

2016-09-29 15:16 UTC, ramereth commented
@LyonesGamer can you also add unit tests for this change please?

2016-09-29 15:19 UTC, ramereth requested changes

2016-09-29 15:19 UTC, ramereth commented on test/integration/default/serverspec/test_tmp_clear_spec.rb
> +  its(:exit_status) { should eq 0 }
You actually want this to return 1. See the grep man page for more details.

2016-09-30 19:32 UTC, ramereth approved these changes

2016-09-30 20:03 UTC, merged

2016-09-30 20:06 UTC, LyonesGamer commented
!bump minor